AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - "Gemfile"
    - "vendor/**/**"
  NewCops: enable
  SuggestExtensions: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/**"

Style/Documentation:
  Enabled: false
